### ISSUE TITLE
OSX Support?

### ISSUE THREAD

**Issue by carcus88** [azawawi/perl6-electron#2]
Everything installs on OS X but can't run any examples, I get this error. Any ideas where to go from here?

![image](https://cloud.githubusercontent.com/assets/95110/17600213/73cb5e4a-5fd0-11e6-9f5c-3d06347d7cdf.png)

**Comment by azawawi** [comment]
@carcus88 I just tested it on OSX after the latest fixes. It now works. Sorry for the delay on this one.
